/**
 * Permission handler comparable callback
 */

/**
 * Permission handler response
 */

/**
 * Permission handler
 */

export let PitchDetectorErrors = /*#__PURE__*/function (PitchDetectorErrors) {
  PitchDetectorErrors[PitchDetectorErrors["BASE"] = 0] = "BASE";
  PitchDetectorErrors[PitchDetectorErrors["LINKING_ERROR"] = 1] = "LINKING_ERROR";
  PitchDetectorErrors[PitchDetectorErrors["PERMISSIONS_ERROR"] = 2] = "PERMISSIONS_ERROR";
  return PitchDetectorErrors;
}({});

/**
 * Event emitter subscription
 */

/**
 * Available musical tones.
 * @see `https://en.wikipedia.org/wiki/Musical_tone`
 */

/**
 * Result generated by pitch estimation process.
 */

/**
 * A callback function called by event emitted from native side.
 */

/**
 * Available pitch estimation algorithm for Android.
 * @see `https://0110.be/releases/TarsosDSP/TarsosDSP-latest/TarsosDSP-latest-Documentation/`
 */

/**
 * Available pitch estimation algorithm for IOS.
 * @see `https://github.com/vadymmarkov/Beethoven#configuration`
 */

/**
 * Pitch detector configuration.
 */

/**
 * PitchDetector native module interface
 */
//# sourceMappingURL=index.js.map